[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 304

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
